ENH : add ALI_IOS on windows with SlicerConda
DCBIA-OrthoLab/SlicerAutomatedDentalTools pull request #86
Opened 2024-03-11 15:22 UTC by GaelleLeroux

Hi @allemangD !

I've made ALI_IOS running on Windows using SlicerConda. Can you give me review and/or merge it if it's ready to be merge ? 

Thank you !
Gaelle

2024-03-18 20:55 UTC, allemangD commented
You'll need to add SlicerConda as a dependency to CMakeLists and to each scripted loadable module that now uses it.

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/main/CMakeLists.txt#L13

https://github.com/DCBIA-OrthoLab/SlicerAutomatedDentalTools/blob/main/ALI/ALI.py#L152

---

Otherwise the changes make sense and should be fine. Thanks!

2024-03-18 21:14 UTC, GaelleLeroux commented
@allemangD 

I made the change, can you merge it if it's good ? 

Thank you ! :)

2024-03-19 13:46 UTC, allemangD requested changes
Sorry if I was overly brief or unclear - I added some review comments with details on what the two fields are used for and what they should be set to.

2024-03-19 13:46 UTC, allemangD commented on ALI/ALI.py
> +    self.parent.dependencies = ["SlicerConda"]  # TODO: add here list of module names that this module requires
This would be the _module_ name `CondaSetUp`, not the extension name. This determines the module load order at Slicer startup.

2024-03-19 13:46 UTC, allemangD commented on CMakeLists.txt
> +set(EXTENSION_DEPENDS "SlicerDentalModelSeg;SlicerConda")# Specified as a list or "NA" if no dependencies
This should be a space-separated list; for example see https://github.com/DCBIA-OrthoLab/SlicerCMF/blob/master/CMakeLists.txt

You're correct this should be the extension name, `SlicerConda`. Specifically it is the name of the relevant `s4ext` in https://github.com/Slicer/ExtensionsIndex/ used at extension installation.

Once this is updated we'll also need to update https://github.com/Slicer/ExtensionsIndex/blob/main/AutomatedDentalTools.s4ext with the same change.

2024-03-19 18:19 UTC, GaelleLeroux commented
@allemangD 

Okay thank you for the explanation ! I tried to make the changes again, are they good ?
I changed SlicerAutomatedDentalTools.s4ext and create a pull request [here](https://github.com/Slicer/ExtensionsIndex/pull/2017)

2024-03-19 18:25 UTC, merged